FROM python:3.10.8-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install debugpy -t /tmp
RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload