version: "3"

services:
  reverse_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
